import type { ModuleRecord } from "@/lib/store";

export function seedApontamentos(): ModuleRecord[] {
  return [
    {
      id: crypto.randomUUID(),
      name: "AP-2024-001",
      meta: {
        codigo: "AP-2024-001",
        op: "OP-2024-001",
        processo: "Corte de Espuma",
        equipamento: "Máquina de Espumação MaxFoam XF-2000",
        operador: "João Silva",
        hora_inicio: "08:00",
        hora_fim: "12:00",
        quantidade_produzida: "25",
        refugo: "1",
        motivo_parada: "",
        observacoes: "Produção normal sem intercorrências",
      },
      createdAt: Date.now(),
    },
    {
      id: crypto.randomUUID(),
      name: "AP-2024-002",
      meta: {
        codigo: "AP-2024-002",
        op: "OP-2024-001",
        processo: "Montagem de Molas",
        equipamento: "Máquina de Montagem de Molas",
        operador: "Maria Santos",
        hora_inicio: "08:30",
        hora_fim: "11:30",
        quantidade_produzida: "20",
        refugo: "0",
        motivo_parada: "",
        observacoes: "Eficiência acima da média",
      },
      createdAt: Date.now(),
    },
    {
      id: crypto.randomUUID(),
      name: "AP-2024-003",
      meta: {
        codigo: "AP-2024-003",
        op: "OP-2024-001",
        processo: "Costura de Capa",
        equipamento: "Bordadeira Brother PR670E",
        operador: "Carlos Oliveira",
        hora_inicio: "09:00",
        hora_fim: "13:00",
        quantidade_produzida: "22",
        refugo: "2",
        motivo_parada: "Qualidade",
        observacoes: "Parada para ajuste na bordadeira",
      },
      createdAt: Date.now(),
    },
    {
      id: crypto.randomUUID(),
      name: "AP-2024-004",
      meta: {
        codigo: "AP-2024-004",
        op: "OP-2024-003",
        processo: "Montagem do Colchão",
        equipamento: "Fechadeira Juki DDL-8700",
        operador: "Ana Paula",
        hora_inicio: "07:00",
        hora_fim: "11:00",
        quantidade_produzida: "30",
        refugo: "0",
        motivo_parada: "",
        observacoes: "Produção concluída antes do prazo",
      },
      createdAt: Date.now(),
    },
    {
      id: crypto.randomUUID(),
      name: "AP-2024-005",
      meta: {
        codigo: "AP-2024-005",
        op: "OP-2024-002",
        processo: "Corte de Espuma",
        equipamento: "Máquina de Espumação MaxFoam XF-2000",
        operador: "Roberto Costa",
        hora_inicio: "08:00",
        hora_fim: "",
        quantidade_produzida: "15",
        refugo: "0",
        motivo_parada: "",
        observacoes: "Apontamento em andamento",
      },
      createdAt: Date.now(),
    },
    {
      id: crypto.randomUUID(),
      name: "AP-2024-006",
      meta: {
        codigo: "AP-2024-006",
        op: "OP-2024-004",
        processo: "Acabamento Final",
        equipamento: "Mesa de Acabamento",
        operador: "João Silva",
        hora_inicio: "08:00",
        hora_fim: "10:00",
        quantidade_produzida: "10",
        refugo: "3",
        motivo_parada: "Falta de Material",
        observacoes: "Parada por falta de tecido",
      },
      createdAt: Date.now(),
    },
  ];
}
