import type { ModuleRecord } from "@/lib/store";

export function seedConsumoMateriais(): ModuleRecord[] {
  return [
    {
      id: crypto.randomUUID(),
      name: "CM-2024-001",
      meta: {
        codigo: "CM-2024-001",
        op: "OP-2024-001",
        material: "Espuma Densidade 33",
        quantidade: "250",
        unidade_medida: "kg",
        data: "2024-01-15",
        processo: "Corte",
        quantidade_padrao: "240",
        desperdicio: "10",
        observacoes: "Desperdício dentro da tolerância",
      },
      createdAt: Date.now(),
    },
    {
      id: crypto.randomUUID(),
      name: "CM-2024-002",
      meta: {
        codigo: "CM-2024-002",
        op: "OP-2024-001",
        material: "Tecido Algodão 100%",
        quantidade: "150",
        unidade_medida: "m",
        data: "2024-01-15",
        processo: "Costura",
        quantidade_padrao: "140",
        desperdicio: "10",
        observacoes: "Desperdício normal de corte",
      },
      createdAt: Date.now(),
    },
    {
      id: crypto.randomUUID(),
      name: "CM-2024-003",
      meta: {
        codigo: "CM-2024-003",
        op: "OP-2024-001",
        material: "Mola Pocket Individual",
        quantidade: "2000",
        unidade_medida: "un",
        data: "2024-01-15",
        processo: "Montagem",
        quantidade_padrao: "2000",
        desperdicio: "0",
        observacoes: "Consumo exato conforme BOM",
      },
      createdAt: Date.now(),
    },
    {
      id: crypto.randomUUID(),
      name: "CM-2024-004",
      meta: {
        codigo: "CM-2024-004",
        op: "OP-2024-003",
        material: "Espuma Densidade 25",
        quantidade: "500",
        unidade_medida: "kg",
        data: "2024-01-10",
        processo: "Corte",
        quantidade_padrao: "480",
        desperdicio: "20",
        observacoes: "Desperdício acima da tolerância - revisar processo",
      },
      createdAt: Date.now(),
    },
    {
      id: crypto.randomUUID(),
      name: "CM-2024-005",
      meta: {
        codigo: "CM-2024-005",
        op: "OP-2024-003",
        material: "Cola Industrial",
        quantidade: "50",
        unidade_medida: "l",
        data: "2024-01-10",
        processo: "Montagem",
        quantidade_padrao: "45",
        desperdicio: "5",
        observacoes: "Consumo normal",
      },
      createdAt: Date.now(),
    },
    {
      id: crypto.randomUUID(),
      name: "CM-2024-006",
      meta: {
        codigo: "CM-2024-006",
        op: "OP-2024-002",
        material: "Espuma Densidade 33",
        quantidade: "150",
        unidade_medida: "kg",
        data: "2024-01-20",
        processo: "Corte",
        quantidade_padrao: "144",
        desperdicio: "6",
        observacoes: "Consumo dentro do esperado",
      },
      createdAt: Date.now(),
    },
    {
      id: crypto.randomUUID(),
      name: "CM-2024-007",
      meta: {
        codigo: "CM-2024-007",
        op: "OP-2024-002",
        material: "Manta Acrílica",
        quantidade: "30",
        unidade_medida: "m²",
        data: "2024-01-20",
        processo: "Acabamento",
        quantidade_padrao: "30",
        desperdicio: "0",
        observacoes: "Consumo exato",
      },
      createdAt: Date.now(),
    },
    {
      id: crypto.randomUUID(),
      name: "CM-2024-008",
      meta: {
        codigo: "CM-2024-008",
        op: "OP-2024-004",
        material: "Tecido Algodão 100%",
        quantidade: "100",
        unidade_medida: "m",
        data: "2024-01-12",
        processo: "Costura",
        quantidade_padrao: "90",
        desperdicio: "10",
        observacoes: "Desperdício por falha na máquina",
      },
      createdAt: Date.now(),
    },
  ];
}
