import type { ModuleRecord } from "@/lib/store";

export function seedEmpresa(): ModuleRecord[] {
  return [
    {
      id: crypto.randomUUID(),
      name: "Ortobom Colchões Industriais Ltda.",
      meta: {
        nomeFantasia: "Ortobom",
        cnpj: "12.345.678/0001-99",
        inscricaoEstadual: "123456789",
        inscricaoMunicipal: "987654321",
        telefone: "(11) 3456-7890",
        email: "contato@ortobom.com.br",
        website: "https://www.ortobom.com.br",
        cep: "01310-100",
        logradouro: "Av. Paulista",
        numero: "1000",
        complemento: "Sala 1501",
        bairro: "Bela Vista",
        cidade: "São Paulo",
        estado: "SP",
        pais: "Brasil",
        latitude: "-23.5505",
        longitude: "-46.6333",
      },
      createdAt: Date.now(),
    },
    {
      id: crypto.randomUUID(),
      name: "Ortobom Filial Rio de Janeiro",
      meta: {
        nomeFantasia: "Ortobom RJ",
        cnpj: "12.345.678/0002-80",
        inscricaoEstadual: "987654321",
        inscricaoMunicipal: "123456789",
        telefone: "(21) 2345-6789",
        email: "filial.rj@ortobom.com.br",
        website: "https://www.ortobom.com.br",
        cep: "20040-002",
        logradouro: "Av. Rio Branco",
        numero: "200",
        complemento: "Centro",
        bairro: "Centro",
        cidade: "Rio de Janeiro",
        estado: "RJ",
        pais: "Brasil",
        latitude: "-22.9068",
        longitude: "-43.1729",
      },
      createdAt: Date.now(),
    },
    {
      id: crypto.randomUUID(),
      name: "Ortobom Filial Minas Gerais",
      meta: {
        nomeFantasia: "Ortobom MG",
        cnpj: "12.345.678/0003-61",
        inscricaoEstadual: "456789123",
        inscricaoMunicipal: "789123456",
        telefone: "(31) 3456-7890",
        email: "filial.mg@ortobom.com.br",
        website: "https://www.ortobom.com.br",
        cep: "30130-010",
        logradouro: "Av. Afonso Pena",
        numero: "1500",
        complemento: "Sala 300",
        bairro: "Centro",
        cidade: "Belo Horizonte",
        estado: "MG",
        pais: "Brasil",
        latitude: "-19.9220",
        longitude: "-43.9450",
      },
      createdAt: Date.now(),
    },
    {
      id: crypto.randomUUID(),
      name: "Ortobom Filial Paraná",
      meta: {
        nomeFantasia: "Ortobom PR",
        cnpj: "12.345.678/0004-42",
        inscricaoEstadual: "789123456",
        inscricaoMunicipal: "456789123",
        telefone: "(41) 2345-6789",
        email: "filial.pr@ortobom.com.br",
        website: "https://www.ortobom.com.br",
        cep: "80020-310",
        logradouro: "Av. Cândido de Abreu",
        numero: "300",
        complemento: "Centro Cívico",
        bairro: "Centro Cívico",
        cidade: "Curitiba",
        estado: "PR",
        pais: "Brasil",
        latitude: "-25.4284",
        longitude: "-49.2733",
      },
      createdAt: Date.now(),
    },
    {
      id: crypto.randomUUID(),
      name: "Ortobom Filial Rio Grande do Sul",
      meta: {
        nomeFantasia: "Ortobom RS",
        cnpj: "12.345.678/0005-23",
        inscricaoEstadual: "321654987",
        inscricaoMunicipal: "654987321",
        telefone: "(51) 3456-7890",
        email: "filial.rs@ortobom.com.br",
        website: "https://www.ortobom.com.br",
        cep: "90010-000",
        logradouro: "Av. Borges de Medeiros",
        numero: "1500",
        complemento: "Centro",
        bairro: "Centro",
        cidade: "Porto Alegre",
        estado: "RS",
        pais: "Brasil",
        latitude: "-30.0346",
        longitude: "-51.2177",
      },
      createdAt: Date.now(),
    },
  ];
}
