import type { ModuleRecord } from "@/lib/store";

export function seedEstoqueIndustrial(): ModuleRecord[] {
  return [
    {
      id: crypto.randomUUID(),
      name: "ESPUMA-D33-PREMIUM",
      meta: {
        codigo: "ESPUMA-D33-PREMIUM",
        nome: "Espuma Densidade 33 Premium",
        categoria: "materia_prima",
        unidade_medida: "kg",
        saldo_atual: 2500,
        saldo_minimo: 500,
        saldo_maximo: 5000,
        localizacao: "Almoxarifado A - Prateleira 1",
        fornecedor: "Espumas do Sul Ltda.",
        classificacao_abc: "a",
        custo_unitario: 45.50,
        observacoes: "Matéria-prima principal para linha Premium",
      },
      createdAt: Date.now(),
    },
    {
      id: crypto.randomUUID(),
      name: "TECIDO-ALGODAO-100",
      meta: {
        codigo: "TECIDO-ALGODAO-100",
        nome: "Tecido Algodão 100%",
        categoria: "materia_prima",
        unidade_medida: "m",
        saldo_atual: 1800,
        saldo_minimo: 300,
        saldo_maximo: 3000,
        localizacao: "Almoxarifado B - Prateleira 2",
        fornecedor: "Têxtil Brasil S.A.",
        classificacao_abc: "a",
        custo_unitario: 28.90,
        observacoes: "Tecido para acabamento de colchões",
      },
      createdAt: Date.now(),
    },
    {
      id: crypto.randomUUID(),
      name: "MOLA-POCKET-INDIVIDUAL",
      meta: {
        codigo: "MOLA-POCKET-INDIVIDUAL",
        nome: "Mola Pocket Individual",
        categoria: "materia_prima",
        unidade_medida: "un",
        saldo_atual: 15000,
        saldo_minimo: 3000,
        saldo_maximo: 25000,
        localizacao: "Almoxarifado C - Prateleira 3",
        fornecedor: "Aços Industriais Ltda.",
        classificacao_abc: "b",
        custo_unitario: 2.50,
        observacoes: "Molas para sistema pocket",
      },
      createdAt: Date.now(),
    },
    {
      id: crypto.randomUUID(),
      name: "COLCHAO-MOLA-CASAL-PREMIUM",
      meta: {
        codigo: "COLCHAO-MOLA-CASAL-PREMIUM",
        nome: "Colchão Mola Pocket Casal Premium",
        categoria: "produto_acabado",
        unidade_medida: "un",
        saldo_atual: 45,
        saldo_minimo: 10,
        saldo_maximo: 100,
        localizacao: "Expedição - Área 1",
        fornecedor: null,
        classificacao_abc: "a",
        custo_unitario: 450.00,
        observacoes: "Produto acabado pronto para entrega",
      },
      createdAt: Date.now(),
    },
    {
      id: crypto.randomUUID(),
      name: "COLCHAO-ESPUMA-KING-LUXO",
      meta: {
        codigo: "COLCHAO-ESPUMA-KING-LUXO",
        nome: "Colchão Espuma D33 King Luxo",
        categoria: "produto_acabado",
        unidade_medida: "un",
        saldo_atual: 28,
        saldo_minimo: 5,
        saldo_maximo: 80,
        localizacao: "Expedição - Área 2",
        fornecedor: null,
        classificacao_abc: "a",
        custo_unitario: 520.00,
        observacoes: "Produto acabado linha Luxo",
      },
      createdAt: Date.now(),
    },
    {
      id: crypto.randomUUID(),
      name: "CAPA-TECIDO-CASAL",
      meta: {
        codigo: "CAPA-TECIDO-CASAL",
        nome: "Capa de Tecido Casal",
        categoria: "semiacabado",
        unidade_medida: "un",
        saldo_atual: 120,
        saldo_minimo: 20,
        saldo_maximo: 200,
        localizacao: "Produção - Estágio 2",
        fornecedor: null,
        classificacao_abc: "b",
        custo_unitario: 85.00,
        observacoes: "Capa pronta para montagem",
      },
      createdAt: Date.now(),
    },
    {
      id: crypto.randomUUID(),
      name: "COLA-INDUSTRIAL-20L",
      meta: {
        codigo: "COLA-INDUSTRIAL-20L",
        nome: "Cola Industrial 20L",
        categoria: "insumos",
        unidade_medida: "un",
        saldo_atual: 45,
        saldo_minimo: 10,
        saldo_maximo: 100,
        localizacao: "Almoxarifado D - Prateleira 4",
        fornecedor: "Química Industrial S.A.",
        classificacao_abc: "c",
        custo_unitario: 120.00,
        observacoes: "Cola para montagem de colchões",
      },
      createdAt: Date.now(),
    },
    {
      id: crypto.randomUUID(),
      name: "EMBALAGEM-PLASTICO-CASAL",
      meta: {
        codigo: "EMBALAGEM-PLASTICO-CASAL",
        nome: "Embalagem Plástico Casal",
        categoria: "embalagens",
        unidade_medida: "un",
        saldo_atual: 500,
        saldo_minimo: 100,
        saldo_maximo: 1000,
        localizacao: "Almoxarifado E - Prateleira 5",
        fornecedor: "Embalagens do Brasil Ltda.",
        classificacao_abc: "c",
        custo_unitario: 8.50,
        observacoes: "Embalagem para transporte",
      },
      createdAt: Date.now(),
    },
  ];
}
