import type { ModuleRecord } from "@/lib/store";

export function seedMovimentacoes(): ModuleRecord[] {
  return [
    {
      id: crypto.randomUUID(),
      name: "MOV-2024-001",
      meta: {
        codigo: "MOV-2024-001",
        tipo: "entrada",
        item_codigo: "ESPUMA-D33-PREMIUM",
        item_nome: "Espuma Densidade 33 Premium",
        quantidade: "1000",
        unidade_medida: "kg",
        data_movimentacao: "2024-01-10",
        hora_movimentacao: "09:30",
        origem: "Fornecedor - Espumas do Sul Ltda.",
        destino: "Almoxarifado A - Prateleira 1",
        documento_tipo: "nf",
        documento_numero: "NF-12345",
        responsavel: "João Silva",
        observacoes: "Entrada de matéria-prima",
      },
      createdAt: Date.now(),
    },
    {
      id: crypto.randomUUID(),
      name: "MOV-2024-002",
      meta: {
        codigo: "MOV-2024-002",
        tipo: "entrada",
        item_codigo: "TECIDO-ALGODAO-100",
        item_nome: "Tecido Algodão 100%",
        quantidade: "800",
        unidade_medida: "m",
        data_movimentacao: "2024-01-12",
        hora_movimentacao: "14:15",
        origem: "Fornecedor - Têxtil Brasil S.A.",
        destino: "Almoxarifado B - Prateleira 2",
        documento_tipo: "nf",
        documento_numero: "NF-12346",
        responsavel: "Maria Santos",
        observacoes: "Entrada de tecido",
      },
      createdAt: Date.now(),
    },
    {
      id: crypto.randomUUID(),
      name: "MOV-2024-003",
      meta: {
        codigo: "MOV-2024-003",
        tipo: "consumo",
        item_codigo: "ESPUMA-D33-PREMIUM",
        item_nome: "Espuma Densidade 33 Premium",
        quantidade: "250",
        unidade_medida: "kg",
        data_movimentacao: "2024-01-15",
        hora_movimentacao: "08:00",
        origem: "Almoxarifado A - Prateleira 1",
        destino: "Produção - Linha 1",
        documento_tipo: "op",
        documento_numero: "OP-2024-001",
        ordem_producao: "OP-2024-001",
        responsavel: "Carlos Oliveira",
        observacoes: "Consumo para produção OP-2024-001",
      },
      createdAt: Date.now(),
    },
    {
      id: crypto.randomUUID(),
      name: "MOV-2024-004",
      meta: {
        codigo: "MOV-2024-004",
        tipo: "producao",
        item_codigo: "COLCHAO-MOLA-CASAL-PREMIUM",
        item_nome: "Colchão Mola Pocket Casal Premium",
        quantidade: "50",
        unidade_medida: "un",
        data_movimentacao: "2024-01-18",
        hora_movimentacao: "17:30",
        origem: "Produção - Linha 1",
        destino: "Expedição - Área 1",
        documento_tipo: "op",
        documento_numero: "OP-2024-001",
        ordem_producao: "OP-2024-001",
        lote: "L-2024-001",
        responsavel: "Roberto Costa",
        observacoes: "Produção concluída da OP-2024-001",
      },
      createdAt: Date.now(),
    },
    {
      id: crypto.randomUUID(),
      name: "MOV-2024-005",
      meta: {
        codigo: "MOV-2024-005",
        tipo: "saida",
        item_codigo: "COLCHAO-MOLA-CASAL-PREMIUM",
        item_nome: "Colchão Mola Pocket Casal Premium",
        quantidade: "5",
        unidade_medida: "un",
        data_movimentacao: "2024-01-19",
        hora_movimentacao: "10:00",
        origem: "Expedição - Área 1",
        destino: "Cliente - Loja Centro",
        documento_tipo: "nf",
        documento_numero: "NF-54321",
        responsavel: "Ana Paula",
        observacoes: "Venda para cliente",
      },
      createdAt: Date.now(),
    },
    {
      id: crypto.randomUUID(),
      name: "MOV-2024-006",
      meta: {
        codigo: "MOV-2024-006",
        tipo: "consumo",
        item_codigo: "TECIDO-ALGODAO-100",
        item_nome: "Tecido Algodão 100%",
        quantidade: "150",
        unidade_medida: "m",
        data_movimentacao: "2024-01-15",
        hora_movimentacao: "08:30",
        origem: "Almoxarifado B - Prateleira 2",
        destino: "Produção - Linha 2",
        documento_tipo: "op",
        documento_numero: "OP-2024-001",
        ordem_producao: "OP-2024-001",
        responsavel: "João Silva",
        observacoes: "Consumo para produção OP-2024-001",
      },
      createdAt: Date.now(),
    },
    {
      id: crypto.randomUUID(),
      name: "MOV-2024-007",
      meta: {
        codigo: "MOV-2024-007",
        tipo: "transferencia",
        item_codigo: "MOLA-POCKET-INDIVIDUAL",
        item_nome: "Mola Pocket Individual",
        quantidade: "2000",
        unidade_medida: "un",
        data_movimentacao: "2024-01-14",
        hora_movimentacao: "11:00",
        origem: "Almoxarifado C - Prateleira 3",
        destino: "Produção - Estágio 1",
        documento_tipo: "transferencia",
        documento_numero: "TR-001",
        responsavel: "Carlos Oliveira",
        observacoes: "Transferência para linha de produção",
      },
      createdAt: Date.now(),
    },
    {
      id: crypto.randomUUID(),
      name: "MOV-2024-008",
      meta: {
        codigo: "MOV-2024-008",
        tipo: "ajuste",
        item_codigo: "COLCHAO-MOLA-CASAL-PREMIUM",
        item_nome: "Colchão Mola Pocket Casal Premium",
        quantidade: "2",
        unidade_medida: "un",
        data_movimentacao: "2024-01-17",
        hora_movimentacao: "16:00",
        origem: "Expedição - Área 1",
        destino: "Expedição - Área 1",
        documento_tipo: "ajuste",
        documento_numero: "AJ-001",
        responsavel: "Maria Santos",
        observacoes: "Ajuste de inventário - divergência contagem",
      },
      createdAt: Date.now(),
    },
  ];
}
