import type { ModuleRecord } from "@/lib/store";

export function seedOrdensProducao(): ModuleRecord[] {
  return [
    {
      id: crypto.randomUUID(),
      name: "OP-2024-001",
      meta: {
        numero: "OP-2024-001",
        produto: "Colchão Mola Pocket Casal Premium",
        quantidade: 50,
        unidade_medida: "un",
        prioridade: "alta",
        status: "em_producao",
        data_inicio: "2024-01-15",
        data_previsao: "2024-01-25",
        responsavel: "João Silva",
        observacoes: "Pedido prioritário para cliente VIP",
      },
      createdAt: Date.now(),
    },
    {
      id: crypto.randomUUID(),
      name: "OP-2024-002",
      meta: {
        numero: "OP-2024-002",
        produto: "Colchão Espuma D33 King Luxo",
        quantidade: 30,
        unidade_medida: "un",
        prioridade: "normal",
        status: "planejada",
        data_inicio: "2024-01-20",
        data_previsao: "2024-02-01",
        responsavel: "Maria Santos",
        observacoes: "Produção regular para estoque",
      },
      createdAt: Date.now(),
    },
    {
      id: crypto.randomUUID(),
      name: "OP-2024-003",
      meta: {
        numero: "OP-2024-003",
        produto: "Colchão Mola Pocket Solteiro Standard",
        quantidade: 100,
        unidade_medida: "un",
        prioridade: "normal",
        status: "finalizada",
        data_inicio: "2024-01-05",
        data_previsao: "2024-01-15",
        data_conclusao: "2024-01-14",
        responsavel: "Carlos Oliveira",
        observacoes: "Produção concluída antes do prazo",
      },
      createdAt: Date.now(),
    },
    {
      id: crypto.randomUUID(),
      name: "OP-2024-004",
      meta: {
        numero: "OP-2024-004",
        produto: "Colchão Espuma D25 Casal Econômico",
        quantidade: 75,
        unidade_medida: "un",
        prioridade: "baixa",
        status: "pausada",
        data_inicio: "2024-01-10",
        data_previsao: "2024-01-30",
        responsavel: "Ana Paula",
        observacoes: "Pausada por falta de matéria-prima",
      },
      createdAt: Date.now(),
    },
    {
      id: crypto.randomUUID(),
      name: "OP-2024-005",
      meta: {
        numero: "OP-2024-005",
        produto: "Colchão Mola Pocket Queen Comfort",
        quantidade: 40,
        unidade_medida: "un",
        prioridade: "urgente",
        status: "liberada",
        data_inicio: "2024-01-18",
        data_previsao: "2024-01-22",
        responsavel: "Roberto Costa",
        observacoes: "Urgente - entrega prometida para cliente",
      },
      createdAt: Date.now(),
    },
  ];
}
