import type { ModuleRecord } from "@/lib/store";

export function seedQualidade(): ModuleRecord[] {
  return [
    {
      id: crypto.randomUUID(),
      name: "Q-2024-001",
      meta: {
        codigo: "Q-2024-001",
        op: "OP-2024-001",
        tipo: "inspecao",
        resultado: "aprovado",
        data: "2024-01-15",
        processo: "Corte",
        inspetor: "Maria Santos",
        nao_conformidade: "",
        acao_corretiva: "",
        retrabalho: "nao",
        observacoes: "Inspeção visual aprovada sem restrições",
      },
      createdAt: Date.now(),
    },
    {
      id: crypto.randomUUID(),
      name: "Q-2024-002",
      meta: {
        codigo: "Q-2024-002",
        op: "OP-2024-001",
        tipo: "inspecao",
        resultado: "aprovado",
        data: "2024-01-16",
        processo: "Montagem",
        inspetor: "Carlos Oliveira",
        nao_conformidade: "",
        acao_corretiva: "",
        retrabalho: "nao",
        observacoes: "Montagem conforme especificações técnicas",
      },
      createdAt: Date.now(),
    },
    {
      id: crypto.randomUUID(),
      name: "Q-2024-003",
      meta: {
        codigo: "Q-2024-003",
        op: "OP-2024-003",
        tipo: "nao-conformidade",
        resultado: "reprovado",
        data: "2024-01-10",
        processo: "Corte",
        inspetor: "Ana Paula",
        nao_conformidade: "Corte irregular na espuma, fora da tolerância de 2mm",
        acao_corretiva: "Ajuste na máquina de corte e retrabalho das peças afetadas",
        retrabalho: "sim",
        observacoes: "Lote parcialmente reprovado, 5 peças com defeito",
      },
      createdAt: Date.now(),
    },
    {
      id: crypto.randomUUID(),
      name: "Q-2024-004",
      meta: {
        codigo: "Q-2024-004",
        op: "OP-2024-003",
        tipo: "retrabalho",
        resultado: "aprovado",
        data: "2024-01-11",
        processo: "Corte",
        inspetor: "João Silva",
        nao_conformidade: "",
        acao_corretiva: "Recorte das peças com defeito",
        retrabalho: "sim",
        observacoes: "5 peças retrabalhadas com sucesso",
      },
      createdAt: Date.now(),
    },
    {
      id: crypto.randomUUID(),
      name: "Q-2024-005",
      meta: {
        codigo: "Q-2024-005",
        op: "OP-2024-003",
        tipo: "aprovacao-final",
        resultado: "aprovado",
        data: "2024-01-14",
        processo: "Acabamento",
        inspetor: "Roberto Costa",
        nao_conformidade: "",
        acao_corretiva: "",
        retrabalho: "nao",
        observacoes: "Lote aprovado para expedição após correções",
      },
      createdAt: Date.now(),
    },
    {
      id: crypto.randomUUID(),
      name: "Q-2024-006",
      meta: {
        codigo: "Q-2024-006",
        op: "OP-2024-004",
        tipo: "nao-conformidade",
        resultado: "pendente",
        data: "2024-01-12",
        processo: "Costura",
        inspetor: "Maria Santos",
        nao_conformidade: "Costura irregular na borda da capa",
        acao_corretiva: "Aguardando decisão do supervisor de qualidade",
        retrabalho: "nao",
        observacoes: "Em análise para definir se é retrabalho ou descarte",
      },
      createdAt: Date.now(),
    },
  ];
}
