/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetoresRouteImport } from './routes/setores'
import { Route as RastreabilidadeRouteImport } from './routes/rastreabilidade'
import { Route as QualidadeRouteImport } from './routes/qualidade'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as ProducaoTempoRealRouteImport } from './routes/producao-tempo-real'
import { Route as ProcessosRouteImport } from './routes/processos'
import { Route as PcpRouteImport } from './routes/pcp'
import { Route as OrdensProducaoRouteImport } from './routes/ordens-producao'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MrpRouteImport } from './routes/mrp'
import { Route as MovimentacoesRouteImport } from './routes/movimentacoes'
import { Route as MateriasPrimasRouteImport } from './routes/materias-primas'
import { Route as LotesRouteImport } from './routes/lotes'
import { Route as ImplantacaoRouteImport } from './routes/implantacao'
import { Route as FuncionariosRouteImport } from './routes/funcionarios'
import { Route as FornecedoresRouteImport } from './routes/fornecedores'
import { Route as FerramentasRouteImport } from './routes/ferramentas'
import { Route as EstoqueIndustrialRouteImport } from './routes/estoque-industrial'
import { Route as EquipamentosRouteImport } from './routes/equipamentos'
import { Route as EmpresaRouteImport } from './routes/empresa'
import { Route as CronometragemRouteImport } from './routes/cronometragem'
import { Route as CopilotRouteImport } from './routes/copilot'
import { Route as ConsumoMateriaisRouteImport } from './routes/consumo-materiais'
import { Route as ConfiguracoesModulosRouteImport } from './routes/configuracoes-modulos'
import { Route as ComponentesRouteImport } from './routes/componentes'
import { Route as CapacidadeRouteImport } from './routes/capacidade'
import { Route as BomRouteImport } from './routes/bom'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApresentacoesRouteImport } from './routes/apresentacoes'
import { Route as ApontamentosRouteImport } from './routes/apontamentos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmpresaIndexRouteImport } from './routes/empresa.index'
import { Route as EmpresaNovoRouteImport } from './routes/empresa.novo'
import { Route as EmpresaIdRouteImport } from './routes/empresa.$id'

const SetoresRoute = SetoresRouteImport.update({
  id: '/setores',
  path: '/setores',
  getParentRoute: () => rootRouteImport,
} as any)
const RastreabilidadeRoute = RastreabilidadeRouteImport.update({
  id: '/rastreabilidade',
  path: '/rastreabilidade',
  getParentRoute: () => rootRouteImport,
} as any)
const QualidadeRoute = QualidadeRouteImport.update({
  id: '/qualidade',
  path: '/qualidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProducaoTempoRealRoute = ProducaoTempoRealRouteImport.update({
  id: '/producao-tempo-real',
  path: '/producao-tempo-real',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessosRoute = ProcessosRouteImport.update({
  id: '/processos',
  path: '/processos',
  getParentRoute: () => rootRouteImport,
} as any)
const PcpRoute = PcpRouteImport.update({
  id: '/pcp',
  path: '/pcp',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdensProducaoRoute = OrdensProducaoRouteImport.update({
  id: '/ordens-producao',
  path: '/ordens-producao',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MrpRoute = MrpRouteImport.update({
  id: '/mrp',
  path: '/mrp',
  getParentRoute: () => rootRouteImport,
} as any)
const MovimentacoesRoute = MovimentacoesRouteImport.update({
  id: '/movimentacoes',
  path: '/movimentacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const MateriasPrimasRoute = MateriasPrimasRouteImport.update({
  id: '/materias-primas',
  path: '/materias-primas',
  getParentRoute: () => rootRouteImport,
} as any)
const LotesRoute = LotesRouteImport.update({
  id: '/lotes',
  path: '/lotes',
  getParentRoute: () => rootRouteImport,
} as any)
const ImplantacaoRoute = ImplantacaoRouteImport.update({
  id: '/implantacao',
  path: '/implantacao',
  getParentRoute: () => rootRouteImport,
} as any)
const FuncionariosRoute = FuncionariosRouteImport.update({
  id: '/funcionarios',
  path: '/funcionarios',
  getParentRoute: () => rootRouteImport,
} as any)
const FornecedoresRoute = FornecedoresRouteImport.update({
  id: '/fornecedores',
  path: '/fornecedores',
  getParentRoute: () => rootRouteImport,
} as any)
const FerramentasRoute = FerramentasRouteImport.update({
  id: '/ferramentas',
  path: '/ferramentas',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueIndustrialRoute = EstoqueIndustrialRouteImport.update({
  id: '/estoque-industrial',
  path: '/estoque-industrial',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipamentosRoute = EquipamentosRouteImport.update({
  id: '/equipamentos',
  path: '/equipamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresaRoute = EmpresaRouteImport.update({
  id: '/empresa',
  path: '/empresa',
  getParentRoute: () => rootRouteImport,
} as any)
const CronometragemRoute = CronometragemRouteImport.update({
  id: '/cronometragem',
  path: '/cronometragem',
  getParentRoute: () => rootRouteImport,
} as any)
const CopilotRoute = CopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsumoMateriaisRoute = ConsumoMateriaisRouteImport.update({
  id: '/consumo-materiais',
  path: '/consumo-materiais',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesModulosRoute = ConfiguracoesModulosRouteImport.update({
  id: '/configuracoes-modulos',
  path: '/configuracoes-modulos',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentesRoute = ComponentesRouteImport.update({
  id: '/componentes',
  path: '/componentes',
  getParentRoute: () => rootRouteImport,
} as any)
const CapacidadeRoute = CapacidadeRouteImport.update({
  id: '/capacidade',
  path: '/capacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const BomRoute = BomRouteImport.update({
  id: '/bom',
  path: '/bom',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApresentacoesRoute = ApresentacoesRouteImport.update({
  id: '/apresentacoes',
  path: '/apresentacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApontamentosRoute = ApontamentosRouteImport.update({
  id: '/apontamentos',
  path: '/apontamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresaIndexRoute = EmpresaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmpresaRoute,
} as any)
const EmpresaNovoRoute = EmpresaNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => EmpresaRoute,
} as any)
const EmpresaIdRoute = EmpresaIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EmpresaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apontamentos': typeof ApontamentosRoute
  '/apresentacoes': typeof ApresentacoesRoute
  '/auth': typeof AuthRoute
  '/bom': typeof BomRoute
  '/capacidade': typeof CapacidadeRoute
  '/componentes': typeof ComponentesRoute
  '/configuracoes-modulos': typeof ConfiguracoesModulosRoute
  '/consumo-materiais': typeof ConsumoMateriaisRoute
  '/copilot': typeof CopilotRoute
  '/cronometragem': typeof CronometragemRoute
  '/empresa': typeof EmpresaRouteWithChildren
  '/equipamentos': typeof EquipamentosRoute
  '/estoque-industrial': typeof EstoqueIndustrialRoute
  '/ferramentas': typeof FerramentasRoute
  '/fornecedores': typeof FornecedoresRoute
  '/funcionarios': typeof FuncionariosRoute
  '/implantacao': typeof ImplantacaoRoute
  '/lotes': typeof LotesRoute
  '/materias-primas': typeof MateriasPrimasRoute
  '/movimentacoes': typeof MovimentacoesRoute
  '/mrp': typeof MrpRoute
  '/onboarding': typeof OnboardingRoute
  '/ordens-producao': typeof OrdensProducaoRoute
  '/pcp': typeof PcpRoute
  '/processos': typeof ProcessosRoute
  '/producao-tempo-real': typeof ProducaoTempoRealRoute
  '/produtos': typeof ProdutosRoute
  '/qualidade': typeof QualidadeRoute
  '/rastreabilidade': typeof RastreabilidadeRoute
  '/setores': typeof SetoresRoute
  '/empresa/$id': typeof EmpresaIdRoute
  '/empresa/novo': typeof EmpresaNovoRoute
  '/empresa/': typeof EmpresaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apontamentos': typeof ApontamentosRoute
  '/apresentacoes': typeof ApresentacoesRoute
  '/auth': typeof AuthRoute
  '/bom': typeof BomRoute
  '/capacidade': typeof CapacidadeRoute
  '/componentes': typeof ComponentesRoute
  '/configuracoes-modulos': typeof ConfiguracoesModulosRoute
  '/consumo-materiais': typeof ConsumoMateriaisRoute
  '/copilot': typeof CopilotRoute
  '/cronometragem': typeof CronometragemRoute
  '/equipamentos': typeof EquipamentosRoute
  '/estoque-industrial': typeof EstoqueIndustrialRoute
  '/ferramentas': typeof FerramentasRoute
  '/fornecedores': typeof FornecedoresRoute
  '/funcionarios': typeof FuncionariosRoute
  '/implantacao': typeof ImplantacaoRoute
  '/lotes': typeof LotesRoute
  '/materias-primas': typeof MateriasPrimasRoute
  '/movimentacoes': typeof MovimentacoesRoute
  '/mrp': typeof MrpRoute
  '/onboarding': typeof OnboardingRoute
  '/ordens-producao': typeof OrdensProducaoRoute
  '/pcp': typeof PcpRoute
  '/processos': typeof ProcessosRoute
  '/producao-tempo-real': typeof ProducaoTempoRealRoute
  '/produtos': typeof ProdutosRoute
  '/qualidade': typeof QualidadeRoute
  '/rastreabilidade': typeof RastreabilidadeRoute
  '/setores': typeof SetoresRoute
  '/empresa/$id': typeof EmpresaIdRoute
  '/empresa/novo': typeof EmpresaNovoRoute
  '/empresa': typeof EmpresaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apontamentos': typeof ApontamentosRoute
  '/apresentacoes': typeof ApresentacoesRoute
  '/auth': typeof AuthRoute
  '/bom': typeof BomRoute
  '/capacidade': typeof CapacidadeRoute
  '/componentes': typeof ComponentesRoute
  '/configuracoes-modulos': typeof ConfiguracoesModulosRoute
  '/consumo-materiais': typeof ConsumoMateriaisRoute
  '/copilot': typeof CopilotRoute
  '/cronometragem': typeof CronometragemRoute
  '/empresa': typeof EmpresaRouteWithChildren
  '/equipamentos': typeof EquipamentosRoute
  '/estoque-industrial': typeof EstoqueIndustrialRoute
  '/ferramentas': typeof FerramentasRoute
  '/fornecedores': typeof FornecedoresRoute
  '/funcionarios': typeof FuncionariosRoute
  '/implantacao': typeof ImplantacaoRoute
  '/lotes': typeof LotesRoute
  '/materias-primas': typeof MateriasPrimasRoute
  '/movimentacoes': typeof MovimentacoesRoute
  '/mrp': typeof MrpRoute
  '/onboarding': typeof OnboardingRoute
  '/ordens-producao': typeof OrdensProducaoRoute
  '/pcp': typeof PcpRoute
  '/processos': typeof ProcessosRoute
  '/producao-tempo-real': typeof ProducaoTempoRealRoute
  '/produtos': typeof ProdutosRoute
  '/qualidade': typeof QualidadeRoute
  '/rastreabilidade': typeof RastreabilidadeRoute
  '/setores': typeof SetoresRoute
  '/empresa/$id': typeof EmpresaIdRoute
  '/empresa/novo': typeof EmpresaNovoRoute
  '/empresa/': typeof EmpresaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apontamentos'
    | '/apresentacoes'
    | '/auth'
    | '/bom'
    | '/capacidade'
    | '/componentes'
    | '/configuracoes-modulos'
    | '/consumo-materiais'
    | '/copilot'
    | '/cronometragem'
    | '/empresa'
    | '/equipamentos'
    | '/estoque-industrial'
    | '/ferramentas'
    | '/fornecedores'
    | '/funcionarios'
    | '/implantacao'
    | '/lotes'
    | '/materias-primas'
    | '/movimentacoes'
    | '/mrp'
    | '/onboarding'
    | '/ordens-producao'
    | '/pcp'
    | '/processos'
    | '/producao-tempo-real'
    | '/produtos'
    | '/qualidade'
    | '/rastreabilidade'
    | '/setores'
    | '/empresa/$id'
    | '/empresa/novo'
    | '/empresa/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apontamentos'
    | '/apresentacoes'
    | '/auth'
    | '/bom'
    | '/capacidade'
    | '/componentes'
    | '/configuracoes-modulos'
    | '/consumo-materiais'
    | '/copilot'
    | '/cronometragem'
    | '/equipamentos'
    | '/estoque-industrial'
    | '/ferramentas'
    | '/fornecedores'
    | '/funcionarios'
    | '/implantacao'
    | '/lotes'
    | '/materias-primas'
    | '/movimentacoes'
    | '/mrp'
    | '/onboarding'
    | '/ordens-producao'
    | '/pcp'
    | '/processos'
    | '/producao-tempo-real'
    | '/produtos'
    | '/qualidade'
    | '/rastreabilidade'
    | '/setores'
    | '/empresa/$id'
    | '/empresa/novo'
    | '/empresa'
  id:
    | '__root__'
    | '/'
    | '/apontamentos'
    | '/apresentacoes'
    | '/auth'
    | '/bom'
    | '/capacidade'
    | '/componentes'
    | '/configuracoes-modulos'
    | '/consumo-materiais'
    | '/copilot'
    | '/cronometragem'
    | '/empresa'
    | '/equipamentos'
    | '/estoque-industrial'
    | '/ferramentas'
    | '/fornecedores'
    | '/funcionarios'
    | '/implantacao'
    | '/lotes'
    | '/materias-primas'
    | '/movimentacoes'
    | '/mrp'
    | '/onboarding'
    | '/ordens-producao'
    | '/pcp'
    | '/processos'
    | '/producao-tempo-real'
    | '/produtos'
    | '/qualidade'
    | '/rastreabilidade'
    | '/setores'
    | '/empresa/$id'
    | '/empresa/novo'
    | '/empresa/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApontamentosRoute: typeof ApontamentosRoute
  ApresentacoesRoute: typeof ApresentacoesRoute
  AuthRoute: typeof AuthRoute
  BomRoute: typeof BomRoute
  CapacidadeRoute: typeof CapacidadeRoute
  ComponentesRoute: typeof ComponentesRoute
  ConfiguracoesModulosRoute: typeof ConfiguracoesModulosRoute
  ConsumoMateriaisRoute: typeof ConsumoMateriaisRoute
  CopilotRoute: typeof CopilotRoute
  CronometragemRoute: typeof CronometragemRoute
  EmpresaRoute: typeof EmpresaRouteWithChildren
  EquipamentosRoute: typeof EquipamentosRoute
  EstoqueIndustrialRoute: typeof EstoqueIndustrialRoute
  FerramentasRoute: typeof FerramentasRoute
  FornecedoresRoute: typeof FornecedoresRoute
  FuncionariosRoute: typeof FuncionariosRoute
  ImplantacaoRoute: typeof ImplantacaoRoute
  LotesRoute: typeof LotesRoute
  MateriasPrimasRoute: typeof MateriasPrimasRoute
  MovimentacoesRoute: typeof MovimentacoesRoute
  MrpRoute: typeof MrpRoute
  OnboardingRoute: typeof OnboardingRoute
  OrdensProducaoRoute: typeof OrdensProducaoRoute
  PcpRoute: typeof PcpRoute
  ProcessosRoute: typeof ProcessosRoute
  ProducaoTempoRealRoute: typeof ProducaoTempoRealRoute
  ProdutosRoute: typeof ProdutosRoute
  QualidadeRoute: typeof QualidadeRoute
  RastreabilidadeRoute: typeof RastreabilidadeRoute
  SetoresRoute: typeof SetoresRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setores': {
      id: '/setores'
      path: '/setores'
      fullPath: '/setores'
      preLoaderRoute: typeof SetoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rastreabilidade': {
      id: '/rastreabilidade'
      path: '/rastreabilidade'
      fullPath: '/rastreabilidade'
      preLoaderRoute: typeof RastreabilidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qualidade': {
      id: '/qualidade'
      path: '/qualidade'
      fullPath: '/qualidade'
      preLoaderRoute: typeof QualidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producao-tempo-real': {
      id: '/producao-tempo-real'
      path: '/producao-tempo-real'
      fullPath: '/producao-tempo-real'
      preLoaderRoute: typeof ProducaoTempoRealRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processos': {
      id: '/processos'
      path: '/processos'
      fullPath: '/processos'
      preLoaderRoute: typeof ProcessosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pcp': {
      id: '/pcp'
      path: '/pcp'
      fullPath: '/pcp'
      preLoaderRoute: typeof PcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ordens-producao': {
      id: '/ordens-producao'
      path: '/ordens-producao'
      fullPath: '/ordens-producao'
      preLoaderRoute: typeof OrdensProducaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mrp': {
      id: '/mrp'
      path: '/mrp'
      fullPath: '/mrp'
      preLoaderRoute: typeof MrpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movimentacoes': {
      id: '/movimentacoes'
      path: '/movimentacoes'
      fullPath: '/movimentacoes'
      preLoaderRoute: typeof MovimentacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materias-primas': {
      id: '/materias-primas'
      path: '/materias-primas'
      fullPath: '/materias-primas'
      preLoaderRoute: typeof MateriasPrimasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lotes': {
      id: '/lotes'
      path: '/lotes'
      fullPath: '/lotes'
      preLoaderRoute: typeof LotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/implantacao': {
      id: '/implantacao'
      path: '/implantacao'
      fullPath: '/implantacao'
      preLoaderRoute: typeof ImplantacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funcionarios': {
      id: '/funcionarios'
      path: '/funcionarios'
      fullPath: '/funcionarios'
      preLoaderRoute: typeof FuncionariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fornecedores': {
      id: '/fornecedores'
      path: '/fornecedores'
      fullPath: '/fornecedores'
      preLoaderRoute: typeof FornecedoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ferramentas': {
      id: '/ferramentas'
      path: '/ferramentas'
      fullPath: '/ferramentas'
      preLoaderRoute: typeof FerramentasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque-industrial': {
      id: '/estoque-industrial'
      path: '/estoque-industrial'
      fullPath: '/estoque-industrial'
      preLoaderRoute: typeof EstoqueIndustrialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipamentos': {
      id: '/equipamentos'
      path: '/equipamentos'
      fullPath: '/equipamentos'
      preLoaderRoute: typeof EquipamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresa': {
      id: '/empresa'
      path: '/empresa'
      fullPath: '/empresa'
      preLoaderRoute: typeof EmpresaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cronometragem': {
      id: '/cronometragem'
      path: '/cronometragem'
      fullPath: '/cronometragem'
      preLoaderRoute: typeof CronometragemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copilot': {
      id: '/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof CopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consumo-materiais': {
      id: '/consumo-materiais'
      path: '/consumo-materiais'
      fullPath: '/consumo-materiais'
      preLoaderRoute: typeof ConsumoMateriaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes-modulos': {
      id: '/configuracoes-modulos'
      path: '/configuracoes-modulos'
      fullPath: '/configuracoes-modulos'
      preLoaderRoute: typeof ConfiguracoesModulosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/componentes': {
      id: '/componentes'
      path: '/componentes'
      fullPath: '/componentes'
      preLoaderRoute: typeof ComponentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capacidade': {
      id: '/capacidade'
      path: '/capacidade'
      fullPath: '/capacidade'
      preLoaderRoute: typeof CapacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bom': {
      id: '/bom'
      path: '/bom'
      fullPath: '/bom'
      preLoaderRoute: typeof BomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apresentacoes': {
      id: '/apresentacoes'
      path: '/apresentacoes'
      fullPath: '/apresentacoes'
      preLoaderRoute: typeof ApresentacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apontamentos': {
      id: '/apontamentos'
      path: '/apontamentos'
      fullPath: '/apontamentos'
      preLoaderRoute: typeof ApontamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresa/': {
      id: '/empresa/'
      path: '/'
      fullPath: '/empresa/'
      preLoaderRoute: typeof EmpresaIndexRouteImport
      parentRoute: typeof EmpresaRoute
    }
    '/empresa/novo': {
      id: '/empresa/novo'
      path: '/novo'
      fullPath: '/empresa/novo'
      preLoaderRoute: typeof EmpresaNovoRouteImport
      parentRoute: typeof EmpresaRoute
    }
    '/empresa/$id': {
      id: '/empresa/$id'
      path: '/$id'
      fullPath: '/empresa/$id'
      preLoaderRoute: typeof EmpresaIdRouteImport
      parentRoute: typeof EmpresaRoute
    }
  }
}

interface EmpresaRouteChildren {
  EmpresaIdRoute: typeof EmpresaIdRoute
  EmpresaNovoRoute: typeof EmpresaNovoRoute
  EmpresaIndexRoute: typeof EmpresaIndexRoute
}

const EmpresaRouteChildren: EmpresaRouteChildren = {
  EmpresaIdRoute: EmpresaIdRoute,
  EmpresaNovoRoute: EmpresaNovoRoute,
  EmpresaIndexRoute: EmpresaIndexRoute,
}

const EmpresaRouteWithChildren =
  EmpresaRoute._addFileChildren(EmpresaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApontamentosRoute: ApontamentosRoute,
  ApresentacoesRoute: ApresentacoesRoute,
  AuthRoute: AuthRoute,
  BomRoute: BomRoute,
  CapacidadeRoute: CapacidadeRoute,
  ComponentesRoute: ComponentesRoute,
  ConfiguracoesModulosRoute: ConfiguracoesModulosRoute,
  ConsumoMateriaisRoute: ConsumoMateriaisRoute,
  CopilotRoute: CopilotRoute,
  CronometragemRoute: CronometragemRoute,
  EmpresaRoute: EmpresaRouteWithChildren,
  EquipamentosRoute: EquipamentosRoute,
  EstoqueIndustrialRoute: EstoqueIndustrialRoute,
  FerramentasRoute: FerramentasRoute,
  FornecedoresRoute: FornecedoresRoute,
  FuncionariosRoute: FuncionariosRoute,
  ImplantacaoRoute: ImplantacaoRoute,
  LotesRoute: LotesRoute,
  MateriasPrimasRoute: MateriasPrimasRoute,
  MovimentacoesRoute: MovimentacoesRoute,
  MrpRoute: MrpRoute,
  OnboardingRoute: OnboardingRoute,
  OrdensProducaoRoute: OrdensProducaoRoute,
  PcpRoute: PcpRoute,
  ProcessosRoute: ProcessosRoute,
  ProducaoTempoRealRoute: ProducaoTempoRealRoute,
  ProdutosRoute: ProdutosRoute,
  QualidadeRoute: QualidadeRoute,
  RastreabilidadeRoute: RastreabilidadeRoute,
  SetoresRoute: SetoresRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
